# Generated by Django 2.2.3 on 2021-09-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.CharField(max_length=150),
        ),
    ]
