# Generated by Django 2.2.3 on 2021-09-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_grano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grano', models.CharField(blank=True, max_length=15, null=True)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria_grano',
                'verbose_name_plural': 'Categoria_granos',
            },
        ),
        migrations.CreateModel(
            name='Categoria_molido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molido', models.CharField(blank=True, max_length=15, null=True)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria_molido',
                'verbose_name_plural': 'Categoria_molidos',
            },
        ),
        migrations.CreateModel(
            name='Categoria_tostado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tostado', models.CharField(blank=True, max_length=15, null=True)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria_tostado',
                'verbose_name_plural': 'Categoria_tostados',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='tienda')),
                ('precio', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('peso', models.FloatField()),
                ('destacado', models.BooleanField()),
                ('origen', models.CharField(max_length=30)),
                ('productor', models.CharField(max_length=50)),
                ('altura', models.IntegerField()),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('grano', models.ManyToManyField(to='APPTienda.Categoria_grano')),
                ('molido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPTienda.Categoria_molido')),
                ('tostado', models.ManyToManyField(to='APPTienda.Categoria_tostado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
