# Generated by Django 2.2.3 on 2021-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPTienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_grano',
            name='grano',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='categoria_molido',
            name='molido',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='categoria_tostado',
            name='tostado',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
