# Generated by Django 2.2.3 on 2021-09-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPTienda', '0002_auto_20210910_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_grano', models.CharField(max_length=250)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grano',
                'verbose_name_plural': 'Granos',
                'ordering': ['categoria_grano'],
            },
        ),
        migrations.CreateModel(
            name='Molido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_molido', models.CharField(max_length=250)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Molido',
                'verbose_name_plural': 'Molidos',
            },
        ),
        migrations.CreateModel(
            name='Tostado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_tostado', models.CharField(max_length=250)),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tostado',
                'verbose_name_plural': 'Tostados',
                'ordering': ['categoria_tostado'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['titulo'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='grano',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='molido',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tostado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='origen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Categoria_grano',
        ),
        migrations.DeleteModel(
            name='Categoria_molido',
        ),
        migrations.DeleteModel(
            name='Categoria_tostado',
        ),
        migrations.AddField(
            model_name='producto',
            name='granos',
            field=models.ManyToManyField(to='APPTienda.Grano'),
        ),
        migrations.AddField(
            model_name='producto',
            name='molidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APPTienda.Molido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tostados',
            field=models.ManyToManyField(to='APPTienda.Tostado'),
        ),
    ]
