# Generated by Django 2.2.3 on 2021-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='home')),
                ('create', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
