# Generated by Django 2.2.3 on 2021-09-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
